algoritmo "semnome"
//Ler duas variáveis numérica, e apresentar a soma das mesmas, acumulando ou não em outra variável.
// Função :
// Autor : Vitor Hugo Assis Da Silva
// Data : 05/08/2024
// Seção de Declarações 
var
 n1, n2, n3 : real
inicio
      escreva("Por favor, digite um valor: ")
      leia(n1)
      escreva("Por favor, digite mais um valor: ")
      leia(n2)
      n3 <- n1+n2
      escreva("A soma dos dois valores escolhidos, é de:",n3)
      
fimalgoritmo
