algoritmo "semnome"
// CPC = 3.1416 * D, sendo que D = R + R. Perímetro de Círculo
// Autor : Vitor hugo Assis Da Silva
// Data : 05/08/2024
// Seção de Declarações 
var
   raio,perimetro : real

inicio
      escreva("Para o calculo do perímetro do Círculo, informe o valor do raio:")
      leia(raio)
      perimetro <- 2*pi*raio
      escreva("O perímetro do Círculo, é de:", perimetro:7:3)
      

fimalgoritmo
