algoritmo "semnome"
// 11) Ler 3 notas e apresentar a média das mesmas.
// Autor : Vitor Hugo Assis Da Silva
// Data : 06/08/2024
// Seção de Declarações 
var
   n1,n2,n3,media : real
inicio
      escreva("Informe o valor da nota 1:")
      leia(n1)
      escreva("Informe o valor da nota 2:")
      leia(n2)
      escreva("Informe o valor da nota 3:")
      leia(n3)
      media<- (n1+n2+n3)/3
      escreva("A média é", media:7:3)
fimalgoritmo
