algoritmo "semnome"
// Baseado no exercício anterior, faça o mesmo processo sem fazer uso de uma terceira variável.
// Autor : Vitor Hugo Assis Da Silva
// Data : 06/08/2024
// Seção de Declarações 
var
   n1,n2 : real
inicio
      escreva("Digite um valor numérico:")
      leia(n1)
      escreva("Digite, por favor, mais um valor numérico:")
      leia(n2)
      escreva("O resultado da décima parte da subtração dos valores, é de:", (n1+n2)/10)
fimalgoritmo
