algoritmo "semnome"
// Construa um algoritmo que solicite dois valores e apresente a soma de ambos com acréscimo de 18%
// Autor : Vitor Hugo Assis Da Silva
// Data : 08/08/2024
// Seção de Declarações 
var
   n1,n2: real
   
inicio
      escreva("Por favor, digite um valor: ")
      leia(n1)
      escreva("Por favor, digite mais um valor: ")
      leia(n2)
      escreva((n1+n2)*1.18, " representa a soma dos valores, com acréscimo de 18%")
fimalgoritmo
