algoritmo "semnome"
// Construa um algoritmo que solicite o nome e o salário de uma pessoa e apresente o salário reduzido de 12,6%
// Autor : Vitor Hugo Assis Da Silva
// Data : 08/08/2024
// Seção de Declarações 
var
   name: caractere
   wage: real
inicio
      escreva("Por favor, digite seu nome: ")
      leia(name)
      escreva("Por favor, informe seu salário: ")
      leia(wage)
      escreva((wage*0.874), " reais representa seu salário após uma redução de 12,6%")
fimalgoritmo
