algoritmo "semnome"
// Construa um algoritmo que solicite dois valores e apresente a soma dos mesmos descontado de 58%
// Autor :   Vitor Hugo Assis Da Silva
// Data : 08/08/2024
// Seção de Declarações 
var
   n1,n2: real
inicio
      escreva("Por favor, digite um número: ")
      leia(n1)
      escreva("Por favor, digite mais um número: ")
      leia(n2)
      escreva((n1+n2)*0.42, " representa a soma dos valores informados, descontando 58%")
fimalgoritmo
