algoritmo "semnome"
// Solicite dois valores e apresente o resto da divisão da soma dos mesmos por 3

// Autor : Vitor Hugo Assis Da Silva
// Data : 08/08/2024
// Seção de Declarações 
var
   n1,n2: inteiro
   
inicio
      escreva("Por favor, digite um valor: ")
      leia(n1)
      escreva("Por favor, digite um valor: ")
      leia(n2)
      escreva((n1+n2)%3, " representa o resto da divisão por 3, referente a soma dos 2 valores informados")
fimalgoritmo
