algoritmo "semnome"
// 12)Solicite uma string e apresente-a caractere a caractere, linha a linha.
//Exemplo: JOSE
//J
//O
//S
//E
// Autor : Vitor hugo assis da silva
// Data : 09/09/2024
// Seção de Declarações 
var

pal,c:caracter
x,comp:inteiro

inicio
x<-0
comp<-0


enquanto (compr(pal)=0) faca
   escreva("Digite uma string: ")
   leia(pal)
fimenquanto

comp<-compr(pal)

para x de 1 ate comp faca
   c<- copia(pal,x,1)
   escreval(c)
fimpara






fimalgoritmo
