algoritmo "semnome"
// Função : Solicite uma string (mínimo 10 caracteres) e apresente apenas do 3o ao 6o
//caractere.
// Autor : vitor hugo assis da silva
// Data : 05/09/2024
// Seção de Declarações 
var
pal,c:caracter
x:inteiro
inicio
enquanto compr(pal)<10 faca
escreva("Digite uma palavra de no mínimo 10 caracteres: ")
leia(pal)
fimenquanto

c<-copia(pal,3,4)
escreval("-----------------------------------------------------------------------------------")
escreva(c)












fimalgoritmo
