algoritmo "semnome"
// Solicite um número qualquer e informe ao usuário se o mesmo é “PAR” ou se é “IMPAR”
// Autor :  VITOR HUGO ASSIS DA SILVA
// Data : 22/08/2024
// Seção de Declarações
var
num:inteiro
inicio
escreva("Por favor, digite um valor: ")
leia(num)
se (num=0) entao
   escreva ("o numero eh neutro")
senao
   se (num%2=0) entao
      escreva("o numero eh par")
   senao
      escreva("o numero eh impar")
   fimse
fimse

fimalgoritmo
