algoritmo "semnome"
// Solicite um número qualquer e informe ao usuário se o mesmo é “PAR” ou se é “IMPAR”
// Autor :  Vitor Hugo assis da silva
// Data : 21/08/2024
// Seção de Declarações

//como ele quer qualquer numero (real), ainda nao da pra fazer, ele nao ensinou ainda como se faz nesse caso
var
num: real
inicio
escreva("Por favor, digite um numero qualquer: ")
leia(num)
se (num%2=0) entao
   escreva("O numero eh par") senao
   escreva("O numero eh impar")
fimse

fimalgoritmo
